### ISSUE TITLE
Plot different filling style for black/white moves

### ISSUE THREAD

**Issue by MrPiada** [Destaq/chess_graph#11]
Like in the example that you reported from this site: https://blog.ebemunk.com/a-visual-look-at-2-million-chess-games/

![image](https://user-images.githubusercontent.com/32706712/100539514-6724ff00-3237-11eb-888f-e2fbfc9ceb84.png)

you can see that odd/even moves have a darker/lighter background

**Comment by Destaq** [comment]
As this program performs the additional functionality of highlighting "segments" based on win ratio, this is not a feature that I would like to implement as it would render the win-ratio shading useless.
